// <auto-generated />
namespace woo.data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class first : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(first));
        
        string IMigrationMetadata.Id
        {
            get { return "201312131914482_first"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
